#!/bin/bash

export PACKAGE_CORE_NAME="gztemplate"
export PACKAGE_CORE_VERSION=v1.0.0
export PACKAGE_CORE_ORG="go-zoox"

export PACKAGE_CORE_GIT_REPOSITORY="https://github.com/${PACKAGE_CORE_ORG}/gztemplate"
export PACKAGE_CORE_RELEASE_DOWNLOAD="${PACKAGE_CORE_GIT_REPOSITORY}/releases/download"
